---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Build TGN
        run: make build BUILD_TYPE=${{ matrix.build_type }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.build_type }}
          path: build/

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Download Debug Build
        uses: actions/download-artifact@v4
        with:
          name: build-Debug
          path: build/

      - name: Run Tests
        run: make test

  cpp-lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Download Debug Build
        uses: actions/download-artifact@v4
        with:
          name: build-Debug
          path: build/

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          database: "build"
          style: "file" # Use .clang-format config file
          tidy-checks: "" # Use .clang-tidy config file
