---
name: Integration Tests

on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Clang Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev libomp-18-dev

      - name: Install OpenMP (MacOS)
        if: runner.os == 'macOS'
        run: brew install libomp

      - name: Build TGN (Tools + Examples)
        run: make tools examples BUILD_TYPE=Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-Release
          path: build/

  link-pred:
    needs: build-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]
        dataset: [tgbl-wiki] # TODO(kuba): Consider some larger ones too
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.os }}-Release
          path: build/

      - name: Restore Binary Permissions
        run: |
          chmod +x build/examples/tgn_link_pred

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install OpenMP (MacOS)
        if: runner.os == 'macOS'
        run: brew install libomp

      - name: Run Link Prediction
        run: make run-link-${{ matrix.dataset }}

  node-pred:
    needs: build-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]
        dataset: [tgbn-trade] # TODO(kuba): Consider some larger ones too
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.os }}-Release
          path: build/

      - name: Restore Binary Permissions
        run: |
          chmod +x build/examples/tgn_node_pred

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install OpenMP (MacOS)
        if: runner.os == 'macOS'
        run: brew install libomp

      - name: Run Node Prediction
        run: make run-node-${{ matrix.dataset }}

  node-pred-on-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build TGN Container
        run: docker build -t tgn-dev .

      - name: Run Node Prediction
        run: |
          docker run --rm \
            -v "$(pwd):/workspace:Z" \
            tgn-dev /bin/bash -c "make run-node-tgbn-trade"
